services:
### database and cache
# +
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: taskdb
    volumes:
      - task_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - task_bridge
# +
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - task_bridge
### backend
# +
  backend-lumen:
    image: server-lumen
    build:
      context: ./server/lumen
      dockerfile: Dockerfile
    ports:
      - "8787:8000"
    networks:
      - task_bridge
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=taskdb
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    depends_on:
      - db
      - redis
# +
  backend-node:
    image: server-node
    build:
      context: ./server/node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - task_bridge
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
### frontend
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - task_bridge
    environment:
      - API_URL=http://localhost:8787
    depends_on:
      - backend-lumen
      - backend-node
###
networks:
  task_bridge:
    driver: "bridge"
volumes:
  task_data: